# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/Users/James/Box Sync/School/CMPEN 331/frazier_lab7/frazier_lab.cache/wt} [current_project]
set_property parent.project_path {D:/Users/James/Box Sync/School/CMPEN 331/frazier_lab7/frazier_lab.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
read_verilog -library xil_defaultlib {
  {D:/Users/James/Box Sync/School/CMPEN 331/frazier_lab7/frazier_lab.srcs/sources_1/new/data_memory.v}
  {D:/Users/James/Box Sync/School/CMPEN 331/frazier_lab7/frazier_lab.srcs/sources_1/new/dataMux.v}
  {D:/Users/James/Box Sync/School/CMPEN 331/frazier_lab7/frazier_lab.srcs/sources_1/new/shift_two_left.v}
  {D:/Users/James/Box Sync/School/CMPEN 331/frazier_lab7/frazier_lab.srcs/sources_1/new/ALU_B_Mux.v}
  {D:/Users/James/Box Sync/School/CMPEN 331/frazier_lab7/frazier_lab.srcs/sources_1/new/sign_extend.v}
  {D:/Users/James/Box Sync/School/CMPEN 331/frazier_lab7/frazier_lab.srcs/sources_1/new/pcMux.v}
  {D:/Users/James/Box Sync/School/CMPEN 331/frazier_lab7/frazier_lab.srcs/sources_1/new/WN_Input_Mux.v}
  {D:/Users/James/Box Sync/School/CMPEN 331/frazier_lab7/frazier_lab.srcs/sources_1/new/shiftMux.v}
  {D:/Users/James/Box Sync/School/CMPEN 331/frazier_lab7/frazier_lab.srcs/sources_1/new/program_counter.v}
  {D:/Users/James/Box Sync/School/CMPEN 331/frazier_lab7/frazier_lab.srcs/sources_1/new/registerfile.v}
  {D:/Users/James/Box Sync/School/CMPEN 331/frazier_lab7/frazier_lab.srcs/sources_1/new/MIPSALU.v}
  {D:/Users/James/Box Sync/School/CMPEN 331/frazier_lab7/frazier_lab.srcs/sources_1/new/instruction_memory.v}
  {D:/Users/James/Box Sync/School/CMPEN 331/frazier_lab7/frazier_lab.srcs/sources_1/new/ALUControl.v}
  {D:/Users/James/Box Sync/School/CMPEN 331/frazier_lab7/frazier_lab.srcs/sources_1/new/adder.v}
  {D:/Users/James/Box Sync/School/CMPEN 331/frazier_lab7/frazier_lab.srcs/sources_1/new/CPU.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/Users/James/Box Sync/School/CMPEN 331/frazier_lab7/frazier_lab.srcs/constrs_1/new/TimeConstraint.xdc}}
set_property used_in_implementation false [get_files {{D:/Users/James/Box Sync/School/CMPEN 331/frazier_lab7/frazier_lab.srcs/constrs_1/new/TimeConstraint.xdc}}]


synth_design -top CPU -part xc7z010clg400-1


write_checkpoint -force -noxdef CPU.dcp

catch { report_utilization -file CPU_utilization_synth.rpt -pb CPU_utilization_synth.pb }
